import Link from 'next/link';
import {articles} from '../lib/content';
import {pageMetadata, site} from '../lib/site';
import GuideCard from '../components/GuideCard';
import JsonLd from '../components/JsonLd';
export const metadata = pageMetadata('Agentic Payments. Your Agent, Your Rules.', 'Search X. Find a meme coin. Set your limit. Explore agentic payments on Solana with plain-English guides from Veyro Network.');
export default function Home() {
  return <main id="main"><JsonLd data={{'@context':'https://schema.org','@type':'WebSite',name:site.name,url:site.origin,description:'Plain-English guides to agentic payments and the Veyro experience on Solana.'}}/>
  <section className="hero"><div className="hero-grid" aria-hidden="true"/><div className="hero-content"><div className="eyebrow"><span className="status-dot"/> AGENTIC PAYMENTS. HUMAN CONTROL.</div><h1>Give it a task.<br/><span>Keep the control.</span></h1><p className="hero-lead">Search X. Find a meme coin. Set your limit.<br/>Let the agent do the work.</p><div className="hero-actions"><a className="button" href={site.demo}>Try Veyro <span aria-hidden="true">↗</span></a><Link className="button secondary" href="/guides/agentic-payments">Understand agentic payments <span aria-hidden="true">→</span></Link></div>
  <div className="prompt-preview"><div className="preview-top"><span>YOU → AGENT</span><span>Example request</span></div><p>“Search X. Find me the best meme coin.<br className="desktop-break"/> Here’s $100.”</p><div className="preview-bottom"><span>Spend limit <strong>$100</strong></span><span className="preview-note">Your ceiling. Your call.</span></div></div><div className="hero-caption"><span>BUILT AROUND SOLANA</span><span>A SIMPLE ASK. A CLEAR BOUNDARY.</span></div></div></section>
  <section className="section intro"><div><span className="eyebrow">THE IDEA</span><h2>Less searching.<br/>More say.</h2></div><div><p className="large-copy">An agent can help you find your next move. You decide how far it can go.</p><p>Veyro brings the task and the spending limit together. Veyro Network is where you learn what that means—from your first prompt to the result you get back.</p><Link className="text-link" href="/guides/ai-agent-payments">Can an AI agent spend for you? <span aria-hidden="true">↗</span></Link></div></section>
  <section className="section steps-section"><div className="section-heading"><div><span className="eyebrow">FROM ASK TO ACTION</span><h2>Three things to understand.</h2></div><a className="text-link" href={site.product}>Meet Veyro ↗</a></div><div className="steps"><article><span className="step-number">01</span><h3>Say what you want.</h3><p>A short instruction gives the agent a direction. Start with the source and the kind of candidate you want.</p><Link href="/guides/writing-agent-prompts">Write a useful prompt ↗</Link></article><article><span className="step-number">02</span><h3>Draw the line.</h3><p>Choose a spending ceiling. Permission has a boundary, even when the agent is doing the searching.</p><Link href="/guides/agent-spending-limits">Understand your limit ↗</Link></article><article><span className="step-number">03</span><h3>See what happened.</h3><p>A candidate, a blocked action, and a completed transaction mean different things. Know your result.</p><Link href="/guides/understanding-agent-results">Read the outcome ↗</Link></article></div></section>
  <section className="section"><div className="section-heading"><div><span className="eyebrow">START WITH THE BASICS</span><h2>Big ideas. Plain English.</h2></div><Link className="text-link" href="/guides">All {articles.length} guides <span aria-hidden="true">↗</span></Link></div><div className="guide-grid">{articles.slice(0,3).map((article,i)=><GuideCard key={article.slug} article={article} number={i+1}/>)}</div></section>
  <section className="section question-section"><div><span className="eyebrow">YOUR NEXT QUESTION</span><h2>Make the first<br/>run make sense.</h2></div><div className="question-list">{[['search-x-with-an-agent','What should I ask the agent?'],['best-meme-coin-search','What does “best meme coin” mean?'],['wallet-connection-and-permission','What does connecting a wallet allow?'],['why-an-agent-stops','Why did the agent stop?'],['solana-agent-payments','Where does Solana fit?']].map(([slug,label])=><Link key={slug} href={`/guides/${slug}`}><span>{label}</span><span aria-hidden="true">↗</span></Link>)}</div></section>
  <section className="section closing"><span className="eyebrow">YOUR AGENT. YOUR MONEY. YOUR RULES.</span><h2>See the idea in action.</h2><p>One instruction. One visible limit.<br/>Explore the current Veyro demo.</p><a className="button" href={site.demo}>Open Try Veyro <span aria-hidden="true">↗</span></a><p className="fine-print">The $100 request above is illustrative. A spending cap does not guarantee a return.</p></section>
  </main>;
}
